cifsd: fix implicit declaration of function 'locks_alloc_lock'
Randy reported build failure:
 ../fs/cifsd/smb2pdu.c:6655:7: error: implicit declaration of function
 'locks_alloc_lock'; did you mean 'locks_copy_lock'?

This patch add depend on FILE_LOCKING.

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Namjae Jeon <namjae.jeon@samsung.com>