cifssrv: fix build error due to redefinition
/cifssrv/smb2pdu.h:1185:8: error: redefinition of 'struct smb2_file_attr_tag_info'
 struct smb2_file_attr_tag_info {
        ^
/cifssrv/smb2pdu.h:1180:8: note: originally defined here
 struct smb2_file_attr_tag_info {

Signed-off-by: Vivek Trivedi <t.vivek@samsung.com>
Signed-off-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>