cifsd: fix build error of missing include fs.h
In file included from fs/cifsd/misc.c:11:0:
fs/cifsd/misc.h:16:53: error: 'struct file' declared inside parameter list [-Werror]
 int smb_check_shared_mode(struct file *filp, struct cifsd_file *curr_fp);
                                                     ^
fs/cifsd/misc.h:16:53: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
  CC      kernel/kdebugd/aop/aop_report_symbol.o
  CC      kernel/locking/lglock.o
  CC      drivers/char/misc.o
  CC      kernel/kdebugd/agent/mmap_kernel.o
  CC      kernel/locking/rtmutex.o
fs/cifsd/misc.c:66:5: error: conflicting types for 'smb_check_shared_mode'
 int smb_check_shared_mode(struct file *filp, struct cifsd_file *curr_fp)
     ^
In file included from fs/cifsd/misc.c:11:0:
fs/cifsd/misc.h:16:5: note: previous declaration of 'smb_check_shared_mode' was here
 int smb_check_shared_mode(struct file *filp, struct cifsd_file *curr_fp);

Signed-off-by: Namjae Jeon <namjae.jeon@protocolfreedom.org>